# Generated by Django 5.2 on 2025-04-12 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("source", models.CharField(max_length=100)),
                ("published_date", models.DateTimeField()),
                ("technology", models.CharField(max_length=100)),
                ("summary", models.TextField()),
            ],
            options={
                "ordering": ["-published_date"],
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="receive_news_updates",
            field=models.BooleanField(
                default=True,
                help_text="Receive news updates about technologies relevant to your skills",
            ),
        ),
        migrations.CreateModel(
            name="TechNewsSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technology", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_notified", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech_news_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Technology News Subscription",
                "verbose_name_plural": "Technology News Subscriptions",
                "unique_together": {("user", "technology")},
            },
        ),
    ]
