# Generated by Django 5.2 on 2025-04-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_newsarticle_profile_receive_news_updates_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsArticle",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="receive_news_updates",
        ),
        migrations.DeleteModel(
            name="TechNewsSubscription",
        ),
    ]
