# Generated by Django 5.2 on 2025-04-12 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company_name", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("source", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobMarket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("required_skills", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="NetworkingGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "extracted_keywords",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("industries", models.JSONField(blank=True, default=list, null=True)),
                ("companies", models.JSONField(blank=True, default=list, null=True)),
                ("roles", models.JSONField(blank=True, default=list, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
