# Generated by Django 5.2 on 2025-04-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('course_title', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('coursera', 'Coursera'), ('udemy', 'Udemy'), ('edx', 'edX'), ('linkedin', 'LinkedIn Learning'), ('pluralsight', 'Pluralsight'), ('udacity', 'Udacity'), ('other', 'Other')], max_length=50)),
                ('url', models.URLField()),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], max_length=20)),
                ('description', models.TextField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews_count', models.IntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_weeks', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-rating', '-reviews_count'],
            },
        ),
    ]
