# Generated by Django 5.2 on 2025-04-12 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_initial_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkingGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "extracted_keywords",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("industries", models.JSONField(blank=True, default=list, null=True)),
                ("companies", models.JSONField(blank=True, default=list, null=True)),
                ("roles", models.JSONField(blank=True, default=list, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
