services:
  - type: web
    name: career-compass
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn career_advisor.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: career-compass-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: GEMINI_API_KEY
        sync: false
      - key: JSEARCH_API_KEY
        sync: false
      - key: ADZUNA_APP_ID
        sync: false
      - key: ADZUNA_APP_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: true

databases:
  - name: career-compass-db
    databaseName: career_compass
    user: career_compass_user
    plan: free 